# services:
#   qdrant:
#     image: qdrant/qdrant
#     ports:
#       - "6333:6333"
#       - "6334:6334"
#     volumes:
#       - ./qdrant_storage:/qdrant/storage
#     restart: unless-stopped

#   ollama:
#     image: ollama/ollama
#     ports:
#       - "11434:11434"
#     volumes:
#       - ollama_data:/root/.ollama
#     environment:
#       - OLLAMA_HOST=0.0.0.0
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:11434"]
#       interval: 10s
#       timeout: 5s
#       retries: 10
#     # REMOVED the problematic command section

#   app:
#     build: .
#     ports:
#       - "5500:5500"
#     environment:
#       - PORT=5500
#       - QDRANT_URL=http://qdrant:6333
#       - OLLAMA_BASE_URL=http://ollama:11434
#       - NODE_ENV=development
#     depends_on:
#       qdrant:
#         condition: service_started
#       ollama:
#         condition: service_healthy
#     volumes:
#       - .:/app
#       - /app/node_modules
#     restart: unless-stopped

# volumes:
#   # ollama_data:


version: '3.8'

services:
  # Backend Service (Node.js + LangChain.js)
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OLLAMA_URL=http://ollama:11434
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379
      - VERTEX_AI_PROJECT_ID=${VERTEX_AI_PROJECT_ID}  # From .env
    depends_on:
      ollama:
        condition: service_healthy
      qdrant:
        condition: service_started
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Ollama Service (Mistral 7B)
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Requires NVIDIA GPU
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]  
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # (Optional) Nginx Proxy
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./certs:/etc/ssl/certs
  #   depends_on:
  #     - backend

volumes:
  ollama_data:
  qdrant_data:
  redis_data:
