version: '3.8'

services:
  backend:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
      - "9229:9229"  # For debugging
    environment:
      - NODE_ENV=development  # Changed to development for dev target
      - OLLAMA_URL=http://ollama:11434
      - QDRANT_URL=http://qdrant:6333
      - REDIS_URL=redis://:yourstrongpassword@redis:6379  # Single consistent URL with password
      - VERTEX_AI_PROJECT_ID=${VERTEX_AI_PROJECT_ID}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      ollama:
        condition: service_healthy
      qdrant:
        condition: service_started
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: redis-server --requirepass yourstrongpassword
    environment:
      - REDIS_PASSWORD=yourstrongpassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "yourstrongpassword", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  ollama_data:
  qdrant_data:
  redis_data:
